hostname="FREEBSDAKALINTECHVM"
keymap="tr.kbd"
sshd_enable="YES"
moused_nondefault_enable="NO"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
#ifconfig_vtnet0="DHCP"
ifconfig_vtnet0="inet 192.168.122.50 netmask 255.255.255.0"
defaultrouter="192.168.122.1"
mysql_enable="YES"
proftpd_enable="YES"
